connections {
	ikepeer4 {
		local_addrs  = 192.168.1.1
		remote_addrs = 192.168.1.101

		local {
			id = perf1
			auth = psk
		}
		remote {
			id = perf2
			auth = psk
		}
		children {
			flow4 {
				# rekey_time=90
				per_cpu_sas = yes
				# for UDP encap
				# per_cpu_sas = encap
				local_ts  = 10.0.1.0/24
				remote_ts = 10.1.1.0/24
				start_action = route
				#hw_offload = yes
			}
		}
		encap = no
		keyingtries=1
	}

	ikepeer6 {
		local_addrs  = fdff:aaaa:bbbb:1::1
		remote_addrs = fdff:aaaa:bbbb:1::101

		local {
			id = perf1
			auth = psk
		}
		remote {
			id = perf2
			auth = psk
		}

		children {
			flow6 {
				# rekey_time=90
				per_cpu_sas = yes
				# for UDP encap
				# per_cpu_sas = encap
				local_ts  = fdaa:1234:0:1::0/64
				remote_ts = fdaa:1234:1:1::0/64
				start_action = route
				#hw_offload = yes
			}
		}
		keyingtries=1
		encap = no
	}
}
